baseURL = "https://sijiaoh.com/"
defaultContentLanguage = "ja"
title = "sijiaoh.com"
theme = "PaperMod"

[languages]
  [languages.ja]
    languageCode = "ja"
    languageName = "日本語"
    weight = 1
    [languages.ja.params.homeInfoParams]
      Title = "sijiaoh"
      Content = "Railsエンジニア。ドワンゴ勤務。ゲーム開発が趣味。"
  [languages.zh]
    languageCode = "zh"
    languageName = "中文"
    weight = 2
    [languages.zh.params.homeInfoParams]
      Title = "sijiaoh"
      Content = "Rails工程师。在dwango工作。兴趣是游戏开发。"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 3
    [languages.en.params.homeInfoParams]
      Title = "sijiaoh"
      Content = "Rails engineer at dwango. Game dev hobbyist."

[params]
  defaultTheme = "auto"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/sijiaoh"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sijiaoh"

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
